//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeRatingWebsite.MyServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyServices.ConnectionServiceSoap")]
    public interface ConnectionServiceSoap {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu HelloWorldResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        RecipeRatingWebsite.MyServices.HelloWorldResponse HelloWorld(RecipeRatingWebsite.MyServices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices.HelloWorldResponse> HelloWorldAsync(RecipeRatingWebsite.MyServices.HelloWorldRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu _userName z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        RecipeRatingWebsite.MyServices.LoginResponse Login(RecipeRatingWebsite.MyServices.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices.LoginResponse> LoginAsync(RecipeRatingWebsite.MyServices.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public RecipeRatingWebsite.MyServices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(RecipeRatingWebsite.MyServices.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public RecipeRatingWebsite.MyServices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(RecipeRatingWebsite.MyServices.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public RecipeRatingWebsite.MyServices.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(RecipeRatingWebsite.MyServices.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string _userName, string _password) {
            this._userName = _userName;
            this._password = _password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public RecipeRatingWebsite.MyServices.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(RecipeRatingWebsite.MyServices.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConnectionServiceSoapChannel : RecipeRatingWebsite.MyServices.ConnectionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConnectionServiceSoapClient : System.ServiceModel.ClientBase<RecipeRatingWebsite.MyServices.ConnectionServiceSoap>, RecipeRatingWebsite.MyServices.ConnectionServiceSoap {
        
        public ConnectionServiceSoapClient() {
        }
        
        public ConnectionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConnectionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConnectionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConnectionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecipeRatingWebsite.MyServices.HelloWorldResponse RecipeRatingWebsite.MyServices.ConnectionServiceSoap.HelloWorld(RecipeRatingWebsite.MyServices.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            RecipeRatingWebsite.MyServices.HelloWorldRequest inValue = new RecipeRatingWebsite.MyServices.HelloWorldRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices.HelloWorldRequestBody();
            RecipeRatingWebsite.MyServices.HelloWorldResponse retVal = ((RecipeRatingWebsite.MyServices.ConnectionServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices.HelloWorldResponse> RecipeRatingWebsite.MyServices.ConnectionServiceSoap.HelloWorldAsync(RecipeRatingWebsite.MyServices.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices.HelloWorldResponse> HelloWorldAsync() {
            RecipeRatingWebsite.MyServices.HelloWorldRequest inValue = new RecipeRatingWebsite.MyServices.HelloWorldRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices.HelloWorldRequestBody();
            return ((RecipeRatingWebsite.MyServices.ConnectionServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecipeRatingWebsite.MyServices.LoginResponse RecipeRatingWebsite.MyServices.ConnectionServiceSoap.Login(RecipeRatingWebsite.MyServices.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string _userName, string _password) {
            RecipeRatingWebsite.MyServices.LoginRequest inValue = new RecipeRatingWebsite.MyServices.LoginRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices.LoginRequestBody();
            inValue.Body._userName = _userName;
            inValue.Body._password = _password;
            RecipeRatingWebsite.MyServices.LoginResponse retVal = ((RecipeRatingWebsite.MyServices.ConnectionServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices.LoginResponse> RecipeRatingWebsite.MyServices.ConnectionServiceSoap.LoginAsync(RecipeRatingWebsite.MyServices.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices.LoginResponse> LoginAsync(string _userName, string _password) {
            RecipeRatingWebsite.MyServices.LoginRequest inValue = new RecipeRatingWebsite.MyServices.LoginRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices.LoginRequestBody();
            inValue.Body._userName = _userName;
            inValue.Body._password = _password;
            return ((RecipeRatingWebsite.MyServices.ConnectionServiceSoap)(this)).LoginAsync(inValue);
        }
    }
}
