//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeRatingWebsite.MyServices_RecipessService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeRespondDto", Namespace="http://myservices.somee.com/RecipesService")]
    [System.SerializableAttribute()]
    public partial class RecipeRespondDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int UserIdField;
        
        private System.Nullable<System.DateTime> CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlImageField;
        
        private float AvgRatingField;
        
        private int TotalVotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UrlImage {
            get {
                return this.UrlImageField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlImageField, value) != true)) {
                    this.UrlImageField = value;
                    this.RaisePropertyChanged("UrlImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public float AvgRating {
            get {
                return this.AvgRatingField;
            }
            set {
                if ((this.AvgRatingField.Equals(value) != true)) {
                    this.AvgRatingField = value;
                    this.RaisePropertyChanged("AvgRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int TotalVotes {
            get {
                return this.TotalVotesField;
            }
            set {
                if ((this.TotalVotesField.Equals(value) != true)) {
                    this.TotalVotesField = value;
                    this.RaisePropertyChanged("TotalVotes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipe", Namespace="http://myservices.somee.com/RecipesService")]
    [System.SerializableAttribute()]
    public partial class Recipe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlImageField;
        
        private int UserIdField;
        
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RecipeRatingWebsite.MyServices_RecipessService.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UrlImage {
            get {
                return this.UrlImageField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlImageField, value) != true)) {
                    this.UrlImageField = value;
                    this.RaisePropertyChanged("UrlImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public RecipeRatingWebsite.MyServices_RecipessService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://myservices.somee.com/RecipesService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.Nullable<System.DateTime> BirthdayField;
        
        private int GenderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int GenderId {
            get {
                return this.GenderIdField;
            }
            set {
                if ((this.GenderIdField.Equals(value) != true)) {
                    this.GenderIdField = value;
                    this.RaisePropertyChanged("GenderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeAddRequestDto", Namespace="http://myservices.somee.com/RecipesService")]
    [System.SerializableAttribute()]
    public partial class RecipeAddRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UrlImage {
            get {
                return this.UrlImageField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlImageField, value) != true)) {
                    this.UrlImageField = value;
                    this.RaisePropertyChanged("UrlImage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://myservices.somee.com/RecipesService", ConfigurationName="MyServices_RecipessService.RecipesServiceSoap")]
    public interface RecipesServiceSoap {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu GetAllRecipesResult z przestrzeni nazw http://myservices.somee.com/RecipesService nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://myservices.somee.com/RecipesService/GetAllRecipes", ReplyAction="*")]
        RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesResponse GetAllRecipes(RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myservices.somee.com/RecipesService/GetAllRecipes", ReplyAction="*")]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesResponse> GetAllRecipesAsync(RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu GetRecipeByIdResult z przestrzeni nazw http://myservices.somee.com/RecipesService nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://myservices.somee.com/RecipesService/GetRecipeById", ReplyAction="*")]
        RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdResponse GetRecipeById(RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myservices.somee.com/RecipesService/GetRecipeById", ReplyAction="*")]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdResponse> GetRecipeByIdAsync(RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu _recipe z przestrzeni nazw http://myservices.somee.com/RecipesService nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://myservices.somee.com/RecipesService/Add", ReplyAction="*")]
        RecipeRatingWebsite.MyServices_RecipessService.AddResponse Add(RecipeRatingWebsite.MyServices_RecipessService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myservices.somee.com/RecipesService/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_RecipessService.AddResponse> AddAsync(RecipeRatingWebsite.MyServices_RecipessService.AddRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRecipesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRecipes", Namespace="http://myservices.somee.com/RecipesService", Order=0)]
        public RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequestBody Body;
        
        public GetAllRecipesRequest() {
        }
        
        public GetAllRecipesRequest(RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRecipesRequestBody {
        
        public GetAllRecipesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRecipesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRecipesResponse", Namespace="http://myservices.somee.com/RecipesService", Order=0)]
        public RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesResponseBody Body;
        
        public GetAllRecipesResponse() {
        }
        
        public GetAllRecipesResponse(RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myservices.somee.com/RecipesService")]
    public partial class GetAllRecipesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RecipeRatingWebsite.MyServices_RecipessService.RecipeRespondDto[] GetAllRecipesResult;
        
        public GetAllRecipesResponseBody() {
        }
        
        public GetAllRecipesResponseBody(RecipeRatingWebsite.MyServices_RecipessService.RecipeRespondDto[] GetAllRecipesResult) {
            this.GetAllRecipesResult = GetAllRecipesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecipeByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecipeById", Namespace="http://myservices.somee.com/RecipesService", Order=0)]
        public RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequestBody Body;
        
        public GetRecipeByIdRequest() {
        }
        
        public GetRecipeByIdRequest(RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myservices.somee.com/RecipesService")]
    public partial class GetRecipeByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int _id;
        
        public GetRecipeByIdRequestBody() {
        }
        
        public GetRecipeByIdRequestBody(int _id) {
            this._id = _id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecipeByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecipeByIdResponse", Namespace="http://myservices.somee.com/RecipesService", Order=0)]
        public RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdResponseBody Body;
        
        public GetRecipeByIdResponse() {
        }
        
        public GetRecipeByIdResponse(RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myservices.somee.com/RecipesService")]
    public partial class GetRecipeByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RecipeRatingWebsite.MyServices_RecipessService.Recipe GetRecipeByIdResult;
        
        public GetRecipeByIdResponseBody() {
        }
        
        public GetRecipeByIdResponseBody(RecipeRatingWebsite.MyServices_RecipessService.Recipe GetRecipeByIdResult) {
            this.GetRecipeByIdResult = GetRecipeByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://myservices.somee.com/RecipesService", Order=0)]
        public RecipeRatingWebsite.MyServices_RecipessService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(RecipeRatingWebsite.MyServices_RecipessService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myservices.somee.com/RecipesService")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RecipeRatingWebsite.MyServices_RecipessService.RecipeAddRequestDto _recipe;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(RecipeRatingWebsite.MyServices_RecipessService.RecipeAddRequestDto _recipe) {
            this._recipe = _recipe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://myservices.somee.com/RecipesService", Order=0)]
        public RecipeRatingWebsite.MyServices_RecipessService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(RecipeRatingWebsite.MyServices_RecipessService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myservices.somee.com/RecipesService")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RecipeRatingWebsite.MyServices_RecipessService.Recipe AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(RecipeRatingWebsite.MyServices_RecipessService.Recipe AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecipesServiceSoapChannel : RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecipesServiceSoapClient : System.ServiceModel.ClientBase<RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap>, RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap {
        
        public RecipesServiceSoapClient() {
        }
        
        public RecipesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecipesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesResponse RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap.GetAllRecipes(RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequest request) {
            return base.Channel.GetAllRecipes(request);
        }
        
        public RecipeRatingWebsite.MyServices_RecipessService.RecipeRespondDto[] GetAllRecipes() {
            RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequest inValue = new RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequestBody();
            RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesResponse retVal = ((RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap)(this)).GetAllRecipes(inValue);
            return retVal.Body.GetAllRecipesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesResponse> RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap.GetAllRecipesAsync(RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequest request) {
            return base.Channel.GetAllRecipesAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesResponse> GetAllRecipesAsync() {
            RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequest inValue = new RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices_RecipessService.GetAllRecipesRequestBody();
            return ((RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap)(this)).GetAllRecipesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdResponse RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap.GetRecipeById(RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequest request) {
            return base.Channel.GetRecipeById(request);
        }
        
        public RecipeRatingWebsite.MyServices_RecipessService.Recipe GetRecipeById(int _id) {
            RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequest inValue = new RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequestBody();
            inValue.Body._id = _id;
            RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdResponse retVal = ((RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap)(this)).GetRecipeById(inValue);
            return retVal.Body.GetRecipeByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdResponse> RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap.GetRecipeByIdAsync(RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequest request) {
            return base.Channel.GetRecipeByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdResponse> GetRecipeByIdAsync(int _id) {
            RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequest inValue = new RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices_RecipessService.GetRecipeByIdRequestBody();
            inValue.Body._id = _id;
            return ((RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap)(this)).GetRecipeByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecipeRatingWebsite.MyServices_RecipessService.AddResponse RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap.Add(RecipeRatingWebsite.MyServices_RecipessService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public RecipeRatingWebsite.MyServices_RecipessService.Recipe Add(RecipeRatingWebsite.MyServices_RecipessService.RecipeAddRequestDto _recipe) {
            RecipeRatingWebsite.MyServices_RecipessService.AddRequest inValue = new RecipeRatingWebsite.MyServices_RecipessService.AddRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices_RecipessService.AddRequestBody();
            inValue.Body._recipe = _recipe;
            RecipeRatingWebsite.MyServices_RecipessService.AddResponse retVal = ((RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_RecipessService.AddResponse> RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap.AddAsync(RecipeRatingWebsite.MyServices_RecipessService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_RecipessService.AddResponse> AddAsync(RecipeRatingWebsite.MyServices_RecipessService.RecipeAddRequestDto _recipe) {
            RecipeRatingWebsite.MyServices_RecipessService.AddRequest inValue = new RecipeRatingWebsite.MyServices_RecipessService.AddRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices_RecipessService.AddRequestBody();
            inValue.Body._recipe = _recipe;
            return ((RecipeRatingWebsite.MyServices_RecipessService.RecipesServiceSoap)(this)).AddAsync(inValue);
        }
    }
}
