//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeRatingWebsite.MyServices_UsersService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRespondDto", Namespace="http://myservices.somee.com/UsersService")]
    [System.SerializableAttribute()]
    public partial class UserRespondDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.Nullable<System.DateTime> BirthdayField;
        
        private RecipeRatingWebsite.MyServices_UsersService.GenderEnum GenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public RecipeRatingWebsite.MyServices_UsersService.GenderEnum Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenderEnum", Namespace="http://myservices.somee.com/UsersService")]
    public enum GenderEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        unset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        male = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        female = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://myservices.somee.com/UsersService", ConfigurationName="MyServices_UsersService.UsersServiceSoap")]
    public interface UsersServiceSoap {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu GetAllUsersResult z przestrzeni nazw http://myservices.somee.com/UsersService nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://myservices.somee.com/UsersService/GetAllUsers", ReplyAction="*")]
        RecipeRatingWebsite.MyServices_UsersService.GetAllUsersResponse GetAllUsers(RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myservices.somee.com/UsersService/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_UsersService.GetAllUsersResponse> GetAllUsersAsync(RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="http://myservices.somee.com/UsersService", Order=0)]
        public RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="http://myservices.somee.com/UsersService", Order=0)]
        public RecipeRatingWebsite.MyServices_UsersService.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(RecipeRatingWebsite.MyServices_UsersService.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myservices.somee.com/UsersService")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RecipeRatingWebsite.MyServices_UsersService.UserRespondDto[] GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(RecipeRatingWebsite.MyServices_UsersService.UserRespondDto[] GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsersServiceSoapChannel : RecipeRatingWebsite.MyServices_UsersService.UsersServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersServiceSoapClient : System.ServiceModel.ClientBase<RecipeRatingWebsite.MyServices_UsersService.UsersServiceSoap>, RecipeRatingWebsite.MyServices_UsersService.UsersServiceSoap {
        
        public UsersServiceSoapClient() {
        }
        
        public UsersServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecipeRatingWebsite.MyServices_UsersService.GetAllUsersResponse RecipeRatingWebsite.MyServices_UsersService.UsersServiceSoap.GetAllUsers(RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public RecipeRatingWebsite.MyServices_UsersService.UserRespondDto[] GetAllUsers() {
            RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequest inValue = new RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequestBody();
            RecipeRatingWebsite.MyServices_UsersService.GetAllUsersResponse retVal = ((RecipeRatingWebsite.MyServices_UsersService.UsersServiceSoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_UsersService.GetAllUsersResponse> RecipeRatingWebsite.MyServices_UsersService.UsersServiceSoap.GetAllUsersAsync(RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipeRatingWebsite.MyServices_UsersService.GetAllUsersResponse> GetAllUsersAsync() {
            RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequest inValue = new RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequest();
            inValue.Body = new RecipeRatingWebsite.MyServices_UsersService.GetAllUsersRequestBody();
            return ((RecipeRatingWebsite.MyServices_UsersService.UsersServiceSoap)(this)).GetAllUsersAsync(inValue);
        }
    }
}
